### ISSUE TITLE
Submissions List is broken if this form element is used in a form

### ISSUE THREAD

**Issue by svenl77** [BuddyForms/BuddyForms-Profile-Image#2]
Catchable fatal error: Object of class stdClass could not be converted to string in /app/public/wp-content/plugins/buddyforms/includes/admin/submissions.php on line 294
<img width="1414" alt="bildschirmfoto 2019-02-02 um 17 13 47" src="https://user-images.githubusercontent.com/645567/52167120-4b6d7200-270e-11e9-85d6-5e26d58069d9.png">

**Comment by njota08** [comment]
Tested, fixed and closed.
